apiVersion : apps/v1
kind: Deployment
metadata:
  name: "apiscluster-a9f5"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "apiscluster-a9f5"
  template:
    metadata:
      labels:
        app: "apiscluster-a9f5"
    spec:
      containers:
        - name: "apiscluster-a9f5"
          image: "srappsacr.azurecr.io/apiscluster"
          ports:
          - containerPort: 80